### ISSUE TITLE
script/build: Where is the generated Debian package stored?

### ISSUE THREAD

**Issue by DAC324** [atom-community/atom#396]
Hello all,

just ran `script/build --create-debian-package` as per instructions. 
The process apparently completed successfully:
```
$ script/build --create-debian-package
Node:	v16.15.1
Python:	v3.10.5
Installing script runner dependencies
Installing script dependencies
Installing apm
apm  2.6.5-atomic.1.0
npm  6.14.14
node 12.18.3 x64
atom unknown
python 3.10.5
git 2.36.1
Installing modules ✓
Wrote Dependencies Fingerprint: /opt/.cache/yay/atom/src/atom/node_modules/.dependencies-fingerprint e79b23d9fc2438ff65485fe6428f970e778e8d52
Cleaning /opt/.cache/yay/atom/src/atom/out
Copying assets to /opt/.cache/yay/atom/src/atom/out/app
Transpiling packages with custom transpiler configurations in /opt/.cache/yay/atom/src/atom/out/app
Transpiling Babel paths in /opt/.cache/yay/atom/src/atom/out/app
Transpiling CoffeeScript paths in /opt/.cache/yay/atom/src/atom/out/app
Transpiling CSON paths in /opt/.cache/yay/atom/src/atom/out/app
Transpiling PEG.js paths in /opt/.cache/yay/atom/src/atom/out/app
Installing modules ✓
Generating module cache for /opt/.cache/yay/atom/src/atom/out/app
Generating pre-built less cache in /opt/.cache/yay/atom/src/atom/out/app/less-compile-cache
Generating metadata for /opt/.cache/yay/atom/src/atom/out/app/package.json
Generating API docs at /opt/.cache/yay/atom/src/atom/docs/output/atom-api.json
Dumping symbols in /opt/.cache/yay/atom/src/atom/out/symbols
Running electron-packager on /opt/.cache/yay/atom/src/atom/out/app with app name "atom"
Packaging app for platform linux x64 using electron v11.5.0
```
However, I was not able to find the newly created Debian package. Is there anything to be done in addition?

**Comment by DeeDeeG** [comment]
The built package would be stored at `out/atom-amd64.deb`.

I would say pay close attention to the spelling of the `--create-debian-package` flag, as it's long and easy to mistype, and because non-existent or typo'd flags are silently ignored (!) and the build takes a long time. I don't see anything in that output above about building the debian (`.deb`) package.

<details><summary>Sample output when creating the debian package</summary>

```
Creating Debian package for "/home/user/atom/out/atom-dev-1.63.0-dev-d46f5241a-amd64"
Creating Debian package directory structure at "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64"
Copying "/home/user/atom/out/atom-dev-1.63.0-dev-d46f5241a-amd64" to "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/usr/share/atom-dev"
Copying binaries into "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/usr/bin"
Writing control file into "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/DEBIAN"
Writing desktop entry file into "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/usr/share/applications"
Copying icon into "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/usr/share/pixmaps"
Copying license into "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/usr/share/doc/atom-dev"
Copying polkit configuration into "/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64/usr/share"
Generating .deb file from /tmp/atom-dev-1.63.0-dev-d46f5241a-amd64
dpkg-deb: building package 'atom-dev' in '/tmp/atom-dev-1.63.0-dev-d46f5241a-amd64.deb'.
Copying generated package into "/home/user/atom/out/atom-amd64.deb"
```

</details>

I made a script to build just the debian package after the rest of the build is already done. Because I've ended up in this exact situation before. (See below). This should be saved as `script/some-filename.js` so it can import the `script/config.js` file properly.

It does need one line changed to match your actual build. The line is the "packaged app dir" where the build was placed on your computer. Something like `out/atom-dev-1.63.0-dev-d46f5241a-amd64/`.

If you can copy paste build that actual output path (as dynamically created on your actual machine) into this script in the appropriate place, you can build the debian package as a standalone script after the full build is complete:

```js
#!/usr/bin/env node

const path = require('path');

const CONFIG = require('./config');
const createDebianPackage = require('./lib/create-debian-package');

const packagedAppPath = path.join(
  CONFIG.buildOutputPath,
  // <~~ REPLACE THE LINE BELOW WITH THE ACTUAL BUILD OUTPUT PATH ON YOUR COMPUTER, SHOULD BE UNDER out/ ~~>
  'atom-dev-1.51.0-dev-9368c1830-amd64'
);

createDebianPackage(packagedAppPath);
```

(The logic it would take to properly, dynamically compute the "packaged app path" is here: https://github.com/atom-community/atom/blob/v1.60.0/script/lib/package-application.js#L227-L263

I didn't bother to try refactoring that into this script. But doing that would mean you wouldn't need to manually update the script with the specific "packaged app path" on your actual computer.)

**Comment by DAC324** [comment]
Indeed, it looks like I made an error while typing/pasting that flag. 
What appeared strange, though, was that `script/build` complained about a missing `dpkg-deb` command in the first instance. 
After re-installing `dpkg`, at least that error was gone. 

Tried again yesterday, this time with ` --no-bootstrap` amended
```
script/build --no-bootstrap  --create-debian-package
```
and then, a Debian package was indeed created:
```
Generating startup blob with mksnapshot
Moving generated startup blob into "/home/gerd/Download/atom/src/atom/out/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/v8_context_snapshot.bin"
Moving generated startup blob into "/home/gerd/Download/atom/src/atom/out/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/snapshot_blob.bin"
Creating Debian package for "/home/gerd/Download/atom/src/atom/out/atom-dev-1.63.0-dev-b2b1d3e5b-amd64"
Creating Debian package directory structure at "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64"
Copying "/home/gerd/Download/atom/src/atom/out/atom-dev-1.63.0-dev-b2b1d3e5b-amd64" to "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/usr/share/atom-dev"
Copying binaries into "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/usr/bin"
Writing control file into "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/DEBIAN"
Writing desktop entry file into "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/usr/share/applications"
Copying icon into "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/usr/share/pixmaps"
Copying license into "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/usr/share/doc/atom-dev"
Copying polkit configuration into "/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64/usr/share"
Generating .deb file from /tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64
dpkg-deb: Building Package »atom-dev« in »/tmp/atom-dev-1.63.0-dev-b2b1d3e5b-amd64.deb«.
Copying generated package into "/home/gerd/Download/atom/src/atom/out/atom-amd64.deb"
```

**Comment by DAC324** [comment]
Nevertheless, that Debian package built that way, appears to be broken. 
At first, the entry in the `.desktop` file appears to be incorrect:
```
nohup: failed to run '/usr/lib/atom/atom': No such file or directory
```
After correcting the `.desktop` file to point to the correct path `/usr/share/atom-dev/atom`, I only get
```
$ /usr/share/atom-dev/atom
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '../build/Release/nslog.node'
Require stack:
- /usr/share/atom-dev/resources/app.asar/node_modules/nslog/lib/nslog.js
- /usr/share/atom-dev/resources/app.asar/src/main-process/start.js
- /usr/share/atom-dev/resources/app.asar/src/main-process/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/share/atom-dev/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/usr/share/atom-dev/resources/app.asar/node_modules/nslog/lib/nslog.js:15:4)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
```

**Comment by DAC324** [comment]
> I made a script to build just the debian package after the rest of the build is already done. Because I've ended up in this exact situation before. (See below). This should be saved as `script/some-filename.js` so it can import the `script/config.js` file and the `glob` module properly.

That script seems to need some further development :) 
```
$ script/build_debian
Searching for completed Atom build using glob pattern: /home/gerd/Download/atom/src/atom/out/atom-*/
Found Atom build at: undefined
Creating Debian package for "undefined"
node:internal/validators:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.basename (node:path:1309:5)
    at module.exports (/home/gerd/Download/atom/src/atom/script/lib/create-debian-package.js:36:10)
    at Object.<anonymous> (/home/gerd/Download/atom/src/atom/script/build_debian:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
